updates.ignore = [
  # pekko updates are better handled explicitly
  { groupId = "org.apache.pekko" }
]

updates.pin = [
  # Scala 3.3 is a LTS
  { groupId = "org.scala-lang", artifactId = "scala3-library", version = "3.3." }
  # we have too many build plugins that need sbt 1.x
  { groupId = "org.scala-sbt", artifactId = "sbt"  version = "1." }
]

updatePullRequests = "always"
