# Licensed to the Apache Software Foundation (ASF) under one or more
# license agreements; and to You under the Apache License, version 2.0:
#
#   https://www.apache.org/licenses/LICENSE-2.0
#
# This file is part of the Apache Pekko project, which was derived from Akka.
#

name: Publish 1.0 Snapshots

on:
  schedule:
    - cron: "0 2 * * 0"
  workflow_dispatch:

jobs:
  sbt:
    name: sbt publish
    runs-on: ubuntu-latest
    if: github.repository == 'apache/pekko-grpc'
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0
          ref: 1.0.x
          
      - name: Setup Java 8
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: temurin
          java-version: 8    

      - name: Install sbt
        uses: sbt/setup-sbt@6c68d2fe8dfbc0a0534d70101baa2e0420e1a506 # v1.1.9

      - name: Publish
        run: |-
          cp .jvmopts-ci .jvmopts
          sbt +publish
          sbt ++2.13.13! codegen/publish
          sbt ++3.3.3! codegen/publish
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PW: ${{ secrets.NEXUS_PW }}

      - name: Publish Gradle Plugin
        run: cd gradle-plugin && ./gradlew publishToSonatype
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PW: ${{ secrets.NEXUS_PW }}
